-- =========================
-- TODAS AS INFORMAÇÕES
-- =========================

CREATE OR REPLACE FUNCTION buscar_parametros_limnologicos(
            p_instituicao_nome text DEFAULT NULL,
            p_reservatorio_nome text DEFAULT NULL,
            p_data_inicio date DEFAULT NULL,
            p_data_fim date DEFAULT NULL,
            p_limit_param integer DEFAULT 100,
            p_offset_param integer DEFAULT 0
        )
        RETURNS TABLE (
    instituicao_nome text,
    reservatorio_nome text,
    sitio_nome text,
    numero_campanha integer,
    data_inicio_campanha date,
    data_fim_campanha date,
    abioticocoluna_profundidade double precision,
    abioticocoluna_dic double precision,
    abioticocoluna_nt double precision,
    abioticocoluna_pt double precision,
    abioticocoluna_delta13c double precision,
    abioticocoluna_delta15n double precision,
    abioticocoluna_data_medida date,
    abioticocoluna_hora_medida time,
    abioticosuperficie_dic double precision,
    abioticosuperficie_nt double precision,
    abioticosuperficie_pt double precision,
    abioticosuperficie_delta13c double precision,
    abioticosuperficie_delta15n double precision,
    abioticosuperficie_data_medida date,
    abioticosuperficie_hora_medida time,
    aguamateriaorganicasedimento_profundidade double precision,
    aguamateriaorganicasedimento_batimetria double precision,
    aguamateriaorganicasedimento_agua double precision,
    aguamateriaorganicasedimento_materiaorganica double precision,
    aguamateriaorganicasedimento_data_medida date,
    aguamateriaorganicasedimento_hora_medida time,
    bioticocoluna_profundidade double precision,
    bioticocoluna_doc double precision,
    bioticocoluna_toc double precision,
    bioticocoluna_poc double precision,
    bioticocoluna_densidadebacteria double precision,
    bioticocoluna_biomassabacteria double precision,
    bioticocoluna_clorofilaa double precision,
    bioticocoluna_biomassacarbonototalfito double precision,
    bioticocoluna_densidadetotalfito double precision,
    bioticocoluna_biomassazoo double precision,
    bioticocoluna_densidadetotalzoo double precision,
    bioticocoluna_data_medida date,
    bioticocoluna_hora_medida time,
    bioticosuperficie_doc double precision,
    bioticosuperficie_toc double precision,
    bioticosuperficie_poc double precision,
    bioticosuperficie_densidadebacteria double precision,
    bioticosuperficie_biomassabacteria double precision,
    bioticosuperficie_clorofilaa double precision,
    bioticosuperficie_biomassacarbonototalfito double precision,
    bioticosuperficie_densidadetotalfito double precision,
    bioticosuperficie_biomassazoo double precision,
    bioticosuperficie_densidadetotalzoo double precision,
    bioticosuperficie_data_medida date,
    bioticosuperficie_hora_medida time,
    bolhas_profundidade double precision,
    bolhas_nrodefunis integer,
    bolhas_volumecoletado double precision,
    bolhas_co2 double precision,
    bolhas_o2 double precision,
    bolhas_n2 double precision,
    bolhas_ch4 double precision,
    bolhas_n2o double precision,
    bolhas_data_medida date,
    bolhas_hora_medida time,
    camarasolo_ch4 double precision,
    camarasolo_co2 double precision,
    camarasolo_n2o double precision,
    camarasolo_tempar double precision,
    camarasolo_tempsolo double precision,
    camarasolo_vento double precision,
    camarasolo_altitude double precision,
    camarasolo_data_medida date,
    camarasolo_hora_medida time,
    carbono_dc double precision,
    carbono_doc double precision,
    carbono_poc double precision,
    carbono_toc double precision,
    carbono_dic double precision,
    carbono_tc double precision,
    carbono_data_medida date,
    carbono_hora_medida time,
    concentracaogasagua_batimetria double precision,
    concentracaogasagua_altura double precision,
    concentracaogasagua_replica integer,
    concentracaogasagua_ch4 double precision,
    concentracaogasagua_co2 double precision,
    concentracaogasagua_data_medida date,
    concentracaogasagua_hora_medida time,
    concentracaogassedimento_batimetria double precision,
    concentracaogassedimento_profundidadedosedimento double precision,
    concentracaogassedimento_replica integer,
    concentracaogassedimento_ch4 double precision,
    concentracaogassedimento_co2 double precision,
    concentracaogassedimento_data_medida date,
    concentracaogassedimento_hora_medida time,
    difusao_ch4 double precision,
    difusao_co2 double precision,
    difusao_n2o double precision,
    difusao_ph double precision,
    difusao_tempagua double precision,
    difusao_tempar double precision,
    difusao_profundidade double precision,
    difusao_altitude double precision,
    difusao_vento double precision,
    difusao_data_medida date,
    difusao_hora_medida time,
    dupladessorcaoagua_profundidade double precision,
    dupladessorcaoagua_co2 double precision,
    dupladessorcaoagua_o2 double precision,
    dupladessorcaoagua_n2 double precision,
    dupladessorcaoagua_ch4 double precision,
    dupladessorcaoagua_n2o double precision,
    dupladessorcaoagua_data_medida date,
    dupladessorcaoagua_hora_medida time,
    fluxobolhasinpe_profundidade double precision,
    fluxobolhasinpe_ch4 double precision,
    fluxobolhasinpe_ch4_desviopadrao double precision,
    fluxobolhasinpe_ch4_amostras integer,
    fluxobolhasinpe_data_medida date,
    fluxobolhasinpe_hora_medida time,
    fluxocarbono_producaofitoplanctonica double precision,
    fluxocarbono_carbonoorganicoexcretado double precision,
    fluxocarbono_respiracaofito double precision,
    fluxocarbono_producaobacteriana double precision,
    fluxocarbono_respiracaobacteriana double precision,
    fluxocarbono_taxasedimentacao double precision,
    fluxocarbono_data_medida date,
    fluxocarbono_hora_medida time,
    fluxodifusivo_batimetria double precision,
    fluxodifusivo_intervalo text,
    fluxodifusivo_ch4 double precision,
    fluxodifusivo_co2 double precision,
    fluxodifusivo_data_medida date,
    fluxodifusivo_hora_medida time,
    fluxodifusivoinpe_profundidade double precision,
    fluxodifusivoinpe_co2 double precision,
    fluxodifusivoinpe_co2_desviopadrao double precision,
    fluxodifusivoinpe_co2_amostras integer,
    fluxodifusivoinpe_ch4 double precision,
    fluxodifusivoinpe_ch4_desviopadrao double precision,
    fluxodifusivoinpe_ch4_amostras integer,
    fluxodifusivoinpe_data_medida date,
    fluxodifusivoinpe_hora_medida time,
    gasesembolhas_profundidade double precision,
    gasesembolhas_co2 double precision,
    gasesembolhas_o2 double precision,
    gasesembolhas_n2 double precision,
    gasesembolhas_ch4 double precision,
    gasesembolhas_n2o double precision,
    gasesembolhas_data_medida date,
    horiba_profundidade double precision,
    horiba_tempagua double precision,
    horiba_condutividade double precision,
    horiba_ph double precision,
    horiba__do double precision,
    horiba_tds double precision,
    horiba_redox double precision,
    horiba_turbidez double precision,
    horiba_data_medida date,
    ionsnaaguaintersticialdosedimento_profundidade double precision,
    ionsnaaguaintersticialdosedimento_batimetria double precision,
    ionsnaaguaintersticialdosedimento_f double precision,
    ionsnaaguaintersticialdosedimento_cl double precision,
    ionsnaaguaintersticialdosedimento_no2 double precision,
    ionsnaaguaintersticialdosedimento_br double precision,
    ionsnaaguaintersticialdosedimento_no3 double precision,
    ionsnaaguaintersticialdosedimento_po4 double precision,
    ionsnaaguaintersticialdosedimento_so4 double precision,
    ionsnaaguaintersticialdosedimento_na double precision,
    ionsnaaguaintersticialdosedimento_nh4 double precision,
    ionsnaaguaintersticialdosedimento_k double precision,
    ionsnaaguaintersticialdosedimento_mg double precision,
    ionsnaaguaintersticialdosedimento_ca double precision,
    ionsnaaguaintersticialdosedimento_acetato double precision,
    ionsnaaguaintersticialdosedimento_data_medida date,
    ionsnaaguaintersticialdosedimento_hora_medida time,
    medidacampocoluna_profundidade double precision,
    medidacampocoluna_secchi double precision,
    medidacampocoluna_tempagua double precision,
    medidacampocoluna_condutividade double precision,
    medidacampocoluna__do double precision,
    medidacampocoluna_ph double precision,
    medidacampocoluna_turbidez double precision,
    medidacampocoluna_materialemsuspensao double precision,
    medidacampocoluna_intensidadeluminosa double precision,
    medidacampocoluna_data_medida date,
    medidacampocoluna_hora_medida time,
    medidacamposuperficie_secchi double precision,
    medidacamposuperficie_tempagua double precision,
    medidacamposuperficie_condutividade double precision,
    medidacamposuperficie__do double precision,
    medidacamposuperficie_ph double precision,
    medidacamposuperficie_turbidez double precision,
    medidacamposuperficie_materialemsuspensao double precision,
    medidacamposuperficie_data_medida date,
    medidacamposuperficie_hora_medida time,
    nutrientessedimento_profundidade double precision,
    nutrientessedimento_batimetria double precision,
    nutrientessedimento_nh4 double precision,
    nutrientessedimento_no2 double precision,
    nutrientessedimento_no3 double precision,
    nutrientessedimento_po4 double precision,
    nutrientessedimento_ptotal double precision,
    nutrientessedimento_ntotal double precision,
    nutrientessedimento_data_medida date,
    nutrientessedimento_hora_medida time,
    parametrosbiologicosfisicosagua_profundidade double precision,
    parametrosbiologicosfisicosagua_secchi double precision,
    parametrosbiologicosfisicosagua_tempagua double precision,
    parametrosbiologicosfisicosagua_condutividade double precision,
    parametrosbiologicosfisicosagua__do double precision,
    parametrosbiologicosfisicosagua_ph double precision,
    parametrosbiologicosfisicosagua_turbidez double precision,
    parametrosbiologicosfisicosagua_materialemsuspensao double precision,
    parametrosbiologicosfisicosagua_doc double precision,
    parametrosbiologicosfisicosagua_toc double precision,
    parametrosbiologicosfisicosagua_poc double precision,
    parametrosbiologicosfisicosagua_dic double precision,
    parametrosbiologicosfisicosagua_nt double precision,
    parametrosbiologicosfisicosagua_pt double precision,
    parametrosbiologicosfisicosagua_densidadebacteria double precision,
    parametrosbiologicosfisicosagua_biomassabacteria double precision,
    parametrosbiologicosfisicosagua_clorofilaa double precision,
    parametrosbiologicosfisicosagua_biomassacarbonototalfito double precision,
    parametrosbiologicosfisicosagua_densidadetotalfito double precision,
    parametrosbiologicosfisicosagua_biomassazoo double precision,
    parametrosbiologicosfisicosagua_densidadetotalzoo double precision,
    parametrosbiologicosfisicosagua_producaofitoplanctonica double precision,
    parametrosbiologicosfisicosagua_carbonoorganicoexcretado double precision,
    parametrosbiologicosfisicosagua_respiracaofito double precision,
    parametrosbiologicosfisicosagua_producaobacteriana double precision,
    parametrosbiologicosfisicosagua_respiracaobacteriana double precision,
    parametrosbiologicosfisicosagua_taxasedimentacao double precision,
    parametrosbiologicosfisicosagua_delta13c double precision,
    parametrosbiologicosfisicosagua_delta15n double precision,
    parametrosbiologicosfisicosagua_intensidadeluminosa double precision,
    parametrosbiologicosfisicosagua_data_medida date,
    pfq_profundidade double precision,
    pfq_batimetria double precision,
    pfq_tempar double precision,
    pfq_tempagua double precision,
    pfq__do double precision,
    pfq_ph double precision,
    pfq_redox double precision,
    pfq_vento text,
    pfq_data_medida date,
    pfq_hora_medida time,
    tc_profundidade text,
    tc_tc double precision,
    tc_data_medida date,
    variaveisfisicasquimicasdaagua_profundidade double precision,
    variaveisfisicasquimicasdaagua_secchi double precision,
    variaveisfisicasquimicasdaagua_batimetria double precision,
    variaveisfisicasquimicasdaagua_f double precision,
    variaveisfisicasquimicasdaagua_cl double precision,
    variaveisfisicasquimicasdaagua_nno3 double precision,
    variaveisfisicasquimicasdaagua_ppo43 double precision,
    variaveisfisicasquimicasdaagua_sso42 double precision,
    variaveisfisicasquimicasdaagua_li double precision,
    variaveisfisicasquimicasdaagua_na double precision,
    variaveisfisicasquimicasdaagua_nnh4 double precision,
    variaveisfisicasquimicasdaagua_k double precision,
    variaveisfisicasquimicasdaagua_mg double precision,
    variaveisfisicasquimicasdaagua_ca double precision,
    variaveisfisicasquimicasdaagua_clorofila double precision,
    variaveisfisicasquimicasdaagua_feofitina double precision,
    variaveisfisicasquimicasdaagua_turbidez double precision,
    variaveisfisicasquimicasdaagua_nt double precision,
    variaveisfisicasquimicasdaagua_pt double precision,
    variaveisfisicasquimicasdaagua_tdc double precision,
    variaveisfisicasquimicasdaagua_data_medida date,
    variaveisfisicasquimicasdaagua_hora_medida time
        )
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RETURN QUERY

            SELECT
                i.nome AS instituicao_nome, r.nome AS reservatorio_nome, s.nome AS sitio_nome, c.nroCampanha AS numero_campanha, c.datainicio AS data_inicio_campanha, c.datafim AS data_fim_campanha, abioticocoluna.profundidade AS abioticocoluna_profundidade, abioticocoluna.dic AS abioticocoluna_dic, abioticocoluna.nt AS abioticocoluna_nt, abioticocoluna.pt AS abioticocoluna_pt, abioticocoluna.delta13c AS abioticocoluna_delta13c, abioticocoluna.delta15n AS abioticocoluna_delta15n, abioticocoluna.datamedida AS abioticocoluna_data_medida, abioticocoluna.horamedida AS abioticocoluna_hora_medida, abioticosuperficie.dic AS abioticosuperficie_dic, abioticosuperficie.nt AS abioticosuperficie_nt, abioticosuperficie.pt AS abioticosuperficie_pt, abioticosuperficie.delta13c AS abioticosuperficie_delta13c, abioticosuperficie.delta15n AS abioticosuperficie_delta15n, abioticosuperficie.datamedida AS abioticosuperficie_data_medida, abioticosuperficie.horamedida AS abioticosuperficie_hora_medida, aguamateriaorganicasedimento.profundidade AS aguamateriaorganicasedimento_profundidade, aguamateriaorganicasedimento.batimetria AS aguamateriaorganicasedimento_batimetria, aguamateriaorganicasedimento.agua AS aguamateriaorganicasedimento_agua, aguamateriaorganicasedimento.materiaOrganica AS aguamateriaorganicasedimento_materiaOrganica, aguamateriaorganicasedimento.datamedida AS aguamateriaorganicasedimento_data_medida, aguamateriaorganicasedimento.horamedida AS aguamateriaorganicasedimento_hora_medida, bioticocoluna.profundidade AS bioticocoluna_profundidade, bioticocoluna.doc AS bioticocoluna_doc, bioticocoluna.toc AS bioticocoluna_toc, bioticocoluna.poc AS bioticocoluna_poc, bioticocoluna.densidadeBacteria AS bioticocoluna_densidadeBacteria, bioticocoluna.biomassaBacteria AS bioticocoluna_biomassaBacteria, bioticocoluna.clorofilaA AS bioticocoluna_clorofilaA, bioticocoluna.biomassaCarbonoTotalFito AS bioticocoluna_biomassaCarbonoTotalFito, bioticocoluna.densidadeTotalFito AS bioticocoluna_densidadeTotalFito, bioticocoluna.biomassaZoo AS bioticocoluna_biomassaZoo, bioticocoluna.densidadeTotalZoo AS bioticocoluna_densidadeTotalZoo, bioticocoluna.datamedida AS bioticocoluna_data_medida, bioticocoluna.horamedida AS bioticocoluna_hora_medida, bioticosuperficie.doc AS bioticosuperficie_doc, bioticosuperficie.toc AS bioticosuperficie_toc, bioticosuperficie.poc AS bioticosuperficie_poc, bioticosuperficie.densidadeBacteria AS bioticosuperficie_densidadeBacteria, bioticosuperficie.biomassaBacteria AS bioticosuperficie_biomassaBacteria, bioticosuperficie.clorofilaA AS bioticosuperficie_clorofilaA, bioticosuperficie.biomassaCarbonoTotalFito AS bioticosuperficie_biomassaCarbonoTotalFito, bioticosuperficie.densidadeTotalFito AS bioticosuperficie_densidadeTotalFito, bioticosuperficie.biomassaZoo AS bioticosuperficie_biomassaZoo, bioticosuperficie.densidadeTotalZoo AS bioticosuperficie_densidadeTotalZoo, bioticosuperficie.datamedida AS bioticosuperficie_data_medida, bioticosuperficie.horamedida AS bioticosuperficie_hora_medida, bolhas.profundidade AS bolhas_profundidade, bolhas.nroDeFunis AS bolhas_nroDeFunis, bolhas.volumeColetado AS bolhas_volumeColetado, bolhas.co2 AS bolhas_co2, bolhas.o2 AS bolhas_o2, bolhas.n2 AS bolhas_n2, bolhas.ch4 AS bolhas_ch4, bolhas.n2o AS bolhas_n2o, bolhas.datamedida AS bolhas_data_medida, bolhas.horamedida AS bolhas_hora_medida, camarasolo.ch4 AS camarasolo_ch4, camarasolo.co2 AS camarasolo_co2, camarasolo.n2o AS camarasolo_n2o, camarasolo.tempar AS camarasolo_tempar, camarasolo.tempsolo AS camarasolo_tempsolo, camarasolo.vento AS camarasolo_vento, camarasolo.altitude AS camarasolo_altitude, camarasolo.datamedida AS camarasolo_data_medida, camarasolo.horamedida AS camarasolo_hora_medida, carbono.dc AS carbono_dc, carbono.doc AS carbono_doc, carbono.poc AS carbono_poc, carbono.toc AS carbono_toc, carbono.dic AS carbono_dic, carbono.tc AS carbono_tc, carbono.datamedida AS carbono_data_medida, carbono.horamedida AS carbono_hora_medida, concentracaogasagua.batimetria AS concentracaogasagua_batimetria, concentracaogasagua.altura AS concentracaogasagua_altura, concentracaogasagua.replica AS concentracaogasagua_replica, concentracaogasagua.ch4 AS concentracaogasagua_ch4, concentracaogasagua.co2 AS concentracaogasagua_co2, concentracaogasagua.datamedida AS concentracaogasagua_data_medida, concentracaogasagua.horamedida AS concentracaogasagua_hora_medida, concentracaogassedimento.batimetria AS concentracaogassedimento_batimetria, concentracaogassedimento.profundidadeDoSedimento AS concentracaogassedimento_profundidadeDoSedimento, concentracaogassedimento.replica AS concentracaogassedimento_replica, concentracaogassedimento.ch4 AS concentracaogassedimento_ch4, concentracaogassedimento.co2 AS concentracaogassedimento_co2, concentracaogassedimento.datamedida AS concentracaogassedimento_data_medida, concentracaogassedimento.horamedida AS concentracaogassedimento_hora_medida, difusao.ch4 AS difusao_ch4, difusao.co2 AS difusao_co2, difusao.n2o AS difusao_n2o, difusao.ph AS difusao_ph, difusao.tempagua AS difusao_tempagua, difusao.tempar AS difusao_tempar, difusao.profundidade AS difusao_profundidade, difusao.altitude AS difusao_altitude, difusao.vento AS difusao_vento, difusao.datamedida AS difusao_data_medida, difusao.horamedida AS difusao_hora_medida, dupladessorcaoagua.profundidade AS dupladessorcaoagua_profundidade, dupladessorcaoagua.co2 AS dupladessorcaoagua_co2, dupladessorcaoagua.o2 AS dupladessorcaoagua_o2, dupladessorcaoagua.n2 AS dupladessorcaoagua_n2, dupladessorcaoagua.ch4 AS dupladessorcaoagua_ch4, dupladessorcaoagua.n2o AS dupladessorcaoagua_n2o, dupladessorcaoagua.datamedida AS dupladessorcaoagua_data_medida, dupladessorcaoagua.horamedida AS dupladessorcaoagua_hora_medida, fluxobolhasinpe.profundidade AS fluxobolhasinpe_profundidade, fluxobolhasinpe.ch4 AS fluxobolhasinpe_ch4, fluxobolhasinpe.ch4_desviopadrao AS fluxobolhasinpe_ch4_desviopadrao, fluxobolhasinpe.ch4_amostras AS fluxobolhasinpe_ch4_amostras, fluxobolhasinpe.datamedida AS fluxobolhasinpe_data_medida, fluxobolhasinpe.horamedida AS fluxobolhasinpe_hora_medida, fluxocarbono.producaofitoplanctonica AS fluxocarbono_producaofitoplanctonica, fluxocarbono.carbonoorganicoexcretado AS fluxocarbono_carbonoorganicoexcretado, fluxocarbono.respiracaofito AS fluxocarbono_respiracaofito, fluxocarbono.producaobacteriana AS fluxocarbono_producaobacteriana, fluxocarbono.respiracaobacteriana AS fluxocarbono_respiracaobacteriana, fluxocarbono.taxasedimentacao AS fluxocarbono_taxasedimentacao, fluxocarbono.datamedida AS fluxocarbono_data_medida, fluxocarbono.horamedida AS fluxocarbono_hora_medida, fluxodifusivo.batimetria AS fluxodifusivo_batimetria, fluxodifusivo.intervalo AS fluxodifusivo_intervalo, fluxodifusivo.ch4 AS fluxodifusivo_ch4, fluxodifusivo.co2 AS fluxodifusivo_co2, fluxodifusivo.datamedida AS fluxodifusivo_data_medida, fluxodifusivo.horamedida AS fluxodifusivo_hora_medida, fluxodifusivoinpe.profundidade AS fluxodifusivoinpe_profundidade, fluxodifusivoinpe.co2 AS fluxodifusivoinpe_co2, fluxodifusivoinpe.co2_desviopadrao AS fluxodifusivoinpe_co2_desviopadrao, fluxodifusivoinpe.co2_amostras AS fluxodifusivoinpe_co2_amostras, fluxodifusivoinpe.ch4 AS fluxodifusivoinpe_ch4, fluxodifusivoinpe.ch4_desviopadrao AS fluxodifusivoinpe_ch4_desviopadrao, fluxodifusivoinpe.ch4_amostras AS fluxodifusivoinpe_ch4_amostras, fluxodifusivoinpe.datamedida AS fluxodifusivoinpe_data_medida, fluxodifusivoinpe.horamedida AS fluxodifusivoinpe_hora_medida, gasesembolhas.profundidade AS gasesembolhas_profundidade, gasesembolhas.co2 AS gasesembolhas_co2, gasesembolhas.o2 AS gasesembolhas_o2, gasesembolhas.n2 AS gasesembolhas_n2, gasesembolhas.ch4 AS gasesembolhas_ch4, gasesembolhas.n2o AS gasesembolhas_n2o, gasesembolhas.datamedida AS gasesembolhas_data_medida, horiba.profundidade AS horiba_profundidade, horiba.tempagua AS horiba_tempagua, horiba.condutividade AS horiba_condutividade, horiba.ph AS horiba_ph, horiba._do AS horiba__do, horiba.tds AS horiba_tds, horiba.redox AS horiba_redox, horiba.turbidez AS horiba_turbidez, horiba.datamedida AS horiba_data_medida, ionsnaaguaintersticialdosedimento.profundidade AS ionsnaaguaintersticialdosedimento_profundidade, ionsnaaguaintersticialdosedimento.batimetria AS ionsnaaguaintersticialdosedimento_batimetria, ionsnaaguaintersticialdosedimento.f AS ionsnaaguaintersticialdosedimento_f, ionsnaaguaintersticialdosedimento.cl AS ionsnaaguaintersticialdosedimento_cl, ionsnaaguaintersticialdosedimento.no2 AS ionsnaaguaintersticialdosedimento_no2, ionsnaaguaintersticialdosedimento.br AS ionsnaaguaintersticialdosedimento_br, ionsnaaguaintersticialdosedimento.no3 AS ionsnaaguaintersticialdosedimento_no3, ionsnaaguaintersticialdosedimento.po4 AS ionsnaaguaintersticialdosedimento_po4, ionsnaaguaintersticialdosedimento.so4 AS ionsnaaguaintersticialdosedimento_so4, ionsnaaguaintersticialdosedimento.na AS ionsnaaguaintersticialdosedimento_na, ionsnaaguaintersticialdosedimento.nh4 AS ionsnaaguaintersticialdosedimento_nh4, ionsnaaguaintersticialdosedimento.k AS ionsnaaguaintersticialdosedimento_k, ionsnaaguaintersticialdosedimento.mg AS ionsnaaguaintersticialdosedimento_mg, ionsnaaguaintersticialdosedimento.ca AS ionsnaaguaintersticialdosedimento_ca, ionsnaaguaintersticialdosedimento.acetato AS ionsnaaguaintersticialdosedimento_acetato, ionsnaaguaintersticialdosedimento.datamedida AS ionsnaaguaintersticialdosedimento_data_medida, ionsnaaguaintersticialdosedimento.horamedida AS ionsnaaguaintersticialdosedimento_hora_medida, medidacampocoluna.profundidade AS medidacampocoluna_profundidade, medidacampocoluna.secchi AS medidacampocoluna_secchi, medidacampocoluna.tempagua AS medidacampocoluna_tempagua, medidacampocoluna.condutividade AS medidacampocoluna_condutividade, medidacampocoluna._do AS medidacampocoluna__do, medidacampocoluna.ph AS medidacampocoluna_ph, medidacampocoluna.turbidez AS medidacampocoluna_turbidez, medidacampocoluna.materialemsuspensao AS medidacampocoluna_materialemsuspensao, medidacampocoluna.intensidadeluminosa AS medidacampocoluna_intensidadeluminosa, medidacampocoluna.datamedida AS medidacampocoluna_data_medida, medidacampocoluna.horamedida AS medidacampocoluna_hora_medida, medidacamposuperficie.secchi AS medidacamposuperficie_secchi, medidacamposuperficie.tempagua AS medidacamposuperficie_tempagua, medidacamposuperficie.condutividade AS medidacamposuperficie_condutividade, medidacamposuperficie._do AS medidacamposuperficie__do, medidacamposuperficie.ph AS medidacamposuperficie_ph, medidacamposuperficie.turbidez AS medidacamposuperficie_turbidez, medidacamposuperficie.materialemsuspensao AS medidacamposuperficie_materialemsuspensao, medidacamposuperficie.datamedida AS medidacamposuperficie_data_medida, medidacamposuperficie.horamedida AS medidacamposuperficie_hora_medida, nutrientessedimento.profundidade AS nutrientessedimento_profundidade, nutrientessedimento.batimetria AS nutrientessedimento_batimetria, nutrientessedimento.nh4 AS nutrientessedimento_nh4, nutrientessedimento.no2 AS nutrientessedimento_no2, nutrientessedimento.no3 AS nutrientessedimento_no3, nutrientessedimento.po4 AS nutrientessedimento_po4, nutrientessedimento.ptotal AS nutrientessedimento_ptotal, nutrientessedimento.ntotal AS nutrientessedimento_ntotal, nutrientessedimento.datamedida AS nutrientessedimento_data_medida, nutrientessedimento.horamedida AS nutrientessedimento_hora_medida, parametrosbiologicosfisicosagua.profundidade AS parametrosbiologicosfisicosagua_profundidade, parametrosbiologicosfisicosagua.secchi AS parametrosbiologicosfisicosagua_secchi, parametrosbiologicosfisicosagua.tempagua AS parametrosbiologicosfisicosagua_tempagua, parametrosbiologicosfisicosagua.condutividade AS parametrosbiologicosfisicosagua_condutividade, parametrosbiologicosfisicosagua._do AS parametrosbiologicosfisicosagua__do, parametrosbiologicosfisicosagua.ph AS parametrosbiologicosfisicosagua_ph, parametrosbiologicosfisicosagua.turbidez AS parametrosbiologicosfisicosagua_turbidez, parametrosbiologicosfisicosagua.materialemsuspensao AS parametrosbiologicosfisicosagua_materialemsuspensao, parametrosbiologicosfisicosagua.doc AS parametrosbiologicosfisicosagua_doc, parametrosbiologicosfisicosagua.toc AS parametrosbiologicosfisicosagua_toc, parametrosbiologicosfisicosagua.poc AS parametrosbiologicosfisicosagua_poc, parametrosbiologicosfisicosagua.dic AS parametrosbiologicosfisicosagua_dic, parametrosbiologicosfisicosagua.nt AS parametrosbiologicosfisicosagua_nt, parametrosbiologicosfisicosagua.pt AS parametrosbiologicosfisicosagua_pt, parametrosbiologicosfisicosagua.densidadebacteria AS parametrosbiologicosfisicosagua_densidadebacteria, parametrosbiologicosfisicosagua.biomassabacteria AS parametrosbiologicosfisicosagua_biomassabacteria, parametrosbiologicosfisicosagua.clorofilaa AS parametrosbiologicosfisicosagua_clorofilaa, parametrosbiologicosfisicosagua.biomassacarbonototalfito AS parametrosbiologicosfisicosagua_biomassacarbonototalfito, parametrosbiologicosfisicosagua.densidadetotalfito AS parametrosbiologicosfisicosagua_densidadetotalfito, parametrosbiologicosfisicosagua.biomassazoo AS parametrosbiologicosfisicosagua_biomassazoo, parametrosbiologicosfisicosagua.densidadetotalzoo AS parametrosbiologicosfisicosagua_densidadetotalzoo, parametrosbiologicosfisicosagua.producaofitoplanctonica AS parametrosbiologicosfisicosagua_producaofitoplanctonica, parametrosbiologicosfisicosagua.carbonoorganicoexcretado AS parametrosbiologicosfisicosagua_carbonoorganicoexcretado, parametrosbiologicosfisicosagua.respiracaofito AS parametrosbiologicosfisicosagua_respiracaofito, parametrosbiologicosfisicosagua.producaobacteriana AS parametrosbiologicosfisicosagua_producaobacteriana, parametrosbiologicosfisicosagua.respiracaobacteriana AS parametrosbiologicosfisicosagua_respiracaobacteriana, parametrosbiologicosfisicosagua.taxasedimentacao AS parametrosbiologicosfisicosagua_taxasedimentacao, parametrosbiologicosfisicosagua.delta13c AS parametrosbiologicosfisicosagua_delta13c, parametrosbiologicosfisicosagua.delta15n AS parametrosbiologicosfisicosagua_delta15n, parametrosbiologicosfisicosagua.intensidadeluminosa AS parametrosbiologicosfisicosagua_intensidadeluminosa, parametrosbiologicosfisicosagua.datamedida AS parametrosbiologicosfisicosagua_data_medida, pfq.profundidade AS pfq_profundidade, pfq.batimetria AS pfq_batimetria, pfq.tempar AS pfq_tempar, pfq.tempagua AS pfq_tempagua, pfq._do AS pfq__do, pfq.ph AS pfq_ph, pfq.redox AS pfq_redox, pfq.vento AS pfq_vento, pfq.datamedida AS pfq_data_medida, pfq.horamedida AS pfq_hora_medida, tc.profundidade AS tc_profundidade, tc.tc AS tc_tc, tc.datamedida AS tc_data_medida, variaveisfisicasquimicasdaagua.profundidade AS variaveisfisicasquimicasdaagua_profundidade, variaveisfisicasquimicasdaagua.secchi AS variaveisfisicasquimicasdaagua_secchi, variaveisfisicasquimicasdaagua.batimetria AS variaveisfisicasquimicasdaagua_batimetria, variaveisfisicasquimicasdaagua.f AS variaveisfisicasquimicasdaagua_f, variaveisfisicasquimicasdaagua.cl AS variaveisfisicasquimicasdaagua_cl, variaveisfisicasquimicasdaagua.nno3 AS variaveisfisicasquimicasdaagua_nno3, variaveisfisicasquimicasdaagua.ppo43 AS variaveisfisicasquimicasdaagua_ppo43, variaveisfisicasquimicasdaagua.sso42 AS variaveisfisicasquimicasdaagua_sso42, variaveisfisicasquimicasdaagua.li AS variaveisfisicasquimicasdaagua_li, variaveisfisicasquimicasdaagua.na AS variaveisfisicasquimicasdaagua_na, variaveisfisicasquimicasdaagua.nnh4 AS variaveisfisicasquimicasdaagua_nnh4, variaveisfisicasquimicasdaagua.k AS variaveisfisicasquimicasdaagua_k, variaveisfisicasquimicasdaagua.mg AS variaveisfisicasquimicasdaagua_mg, variaveisfisicasquimicasdaagua.ca AS variaveisfisicasquimicasdaagua_ca, variaveisfisicasquimicasdaagua.clorofila AS variaveisfisicasquimicasdaagua_clorofila, variaveisfisicasquimicasdaagua.feofitina AS variaveisfisicasquimicasdaagua_feofitina, variaveisfisicasquimicasdaagua.turbidez AS variaveisfisicasquimicasdaagua_turbidez, variaveisfisicasquimicasdaagua.nt AS variaveisfisicasquimicasdaagua_nt, variaveisfisicasquimicasdaagua.pt AS variaveisfisicasquimicasdaagua_pt, variaveisfisicasquimicasdaagua.tdc AS variaveisfisicasquimicasdaagua_tdc, variaveisfisicasquimicasdaagua.datamedida AS variaveisfisicasquimicasdaagua_data_medida, variaveisfisicasquimicasdaagua.horamedida AS variaveisfisicasquimicasdaagua_hora_medida
            FROM tbcampanha c JOIN tbinstituicao i ON c.idinstituicao = i.idinstituicao JOIN tbreservatorio r ON c.idreservatorio = r.idreservatorio JOIN tbsitio s ON c.idreservatorio = s.idreservatorio LEFT JOIN tbabioticocoluna abioticocoluna ON abioticocoluna.idcampanha = c.idcampanha AND abioticocoluna.idsitio = s.idsitio LEFT JOIN tbabioticosuperficie abioticosuperficie ON abioticosuperficie.idcampanha = c.idcampanha AND abioticosuperficie.idsitio = s.idsitio LEFT JOIN tbaguamateriaorganicasedimento aguamateriaorganicasedimento ON aguamateriaorganicasedimento.idcampanha = c.idcampanha AND aguamateriaorganicasedimento.idsitio = s.idsitio LEFT JOIN tbbioticocoluna bioticocoluna ON bioticocoluna.idcampanha = c.idcampanha AND bioticocoluna.idsitio = s.idsitio LEFT JOIN tbbioticosuperficie bioticosuperficie ON bioticosuperficie.idcampanha = c.idcampanha AND bioticosuperficie.idsitio = s.idsitio LEFT JOIN tbbolhas bolhas ON bolhas.idcampanha = c.idcampanha AND bolhas.idsitio = s.idsitio LEFT JOIN tbcamarasolo camarasolo ON camarasolo.idcampanha = c.idcampanha AND camarasolo.idsitio = s.idsitio LEFT JOIN tbcarbono carbono ON carbono.idcampanha = c.idcampanha AND carbono.idsitio = s.idsitio LEFT JOIN tbconcentracaogasagua concentracaogasagua ON concentracaogasagua.idcampanha = c.idcampanha AND concentracaogasagua.idsitio = s.idsitio LEFT JOIN tbconcentracaogassedimento concentracaogassedimento ON concentracaogassedimento.idcampanha = c.idcampanha AND concentracaogassedimento.idsitio = s.idsitio LEFT JOIN tbdifusao difusao ON difusao.idcampanha = c.idcampanha AND difusao.idsitio = s.idsitio LEFT JOIN tbdupladessorcaoagua dupladessorcaoagua ON dupladessorcaoagua.idcampanha = c.idcampanha AND dupladessorcaoagua.idsitio = s.idsitio LEFT JOIN tbfluxobolhasinpe fluxobolhasinpe ON fluxobolhasinpe.idcampanha = c.idcampanha AND fluxobolhasinpe.idsitio = s.idsitio LEFT JOIN tbfluxocarbono fluxocarbono ON fluxocarbono.idcampanha = c.idcampanha AND fluxocarbono.idsitio = s.idsitio LEFT JOIN tbfluxodifusivo fluxodifusivo ON fluxodifusivo.idcampanha = c.idcampanha AND fluxodifusivo.idsitio = s.idsitio LEFT JOIN tbfluxodifusivoinpe fluxodifusivoinpe ON fluxodifusivoinpe.idcampanha = c.idcampanha AND fluxodifusivoinpe.idsitio = s.idsitio LEFT JOIN tbgasesembolhas gasesembolhas ON gasesembolhas.idcampanha = c.idcampanha AND gasesembolhas.idsitio = s.idsitio LEFT JOIN tbhoriba horiba ON horiba.idcampanha = c.idcampanha AND horiba.idsitio = s.idsitio LEFT JOIN tbionsnaaguaintersticialdosedimento ionsnaaguaintersticialdosedimento ON ionsnaaguaintersticialdosedimento.idcampanha = c.idcampanha AND ionsnaaguaintersticialdosedimento.idsitio = s.idsitio LEFT JOIN tbmedidacampocoluna medidacampocoluna ON medidacampocoluna.idcampanha = c.idcampanha AND medidacampocoluna.idsitio = s.idsitio LEFT JOIN tbmedidacamposuperficie medidacamposuperficie ON medidacamposuperficie.idcampanha = c.idcampanha AND medidacamposuperficie.idsitio = s.idsitio LEFT JOIN tbnutrientessedimento nutrientessedimento ON nutrientessedimento.idcampanha = c.idcampanha AND nutrientessedimento.idsitio = s.idsitio LEFT JOIN tbparametrosbiologicosfisicosagua parametrosbiologicosfisicosagua ON parametrosbiologicosfisicosagua.idcampanha = c.idcampanha AND parametrosbiologicosfisicosagua.idsitio = s.idsitio LEFT JOIN tbpfq pfq ON pfq.idcampanha = c.idcampanha AND pfq.idsitio = s.idsitio LEFT JOIN tbtc tc ON tc.idcampanha = c.idcampanha AND tc.idsitio = s.idsitio LEFT JOIN tbvariaveisfisicasquimicasdaagua variaveisfisicasquimicasdaagua ON variaveisfisicasquimicasdaagua.idcampanha = c.idcampanha AND variaveisfisicasquimicasdaagua.idsitio = s.idsitio
            WHERE (p_instituicao_nome IS NULL OR i.nome = p_instituicao_nome) AND (p_reservatorio_nome IS NULL OR r.nome = p_reservatorio_nome) AND (p_data_inicio IS NULL OR c.datainicio >= p_data_inicio) AND (p_data_fim IS NULL OR c.datafim <= p_data_fim)
            ORDER BY c.datainicio DESC, c.horamedida DESC
            LIMIT p_limit_param
            OFFSET p_offset_param
;
        END;
        $$;


-- =========================
-- TODAS AS COORDENADAS DA INSTITUIÇÃO
-- =========================

CREATE OR REPLACE FUNCTION buscar_coordenadas_instituicao(
    p_instituicao_nome text DEFAULT NULL,
    p_reservatorio_nome text DEFAULT NULL,
    p_limit_param integer DEFAULT 100,
    p_offset_param integer DEFAULT 0
)
RETURNS TABLE (
    idestacao integer,
    idhexadecimal text,
    rotulo text,
    lat double precision,
    lng double precision,
    inicio date,
    fim date,
    reservatorio_nome text,
    instituicao_nome text
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        e.idestacao,
        e.idhexadecimal,
        e.rotulo,
        e.lat,
        e.lng,
        e.inicio,
        e.fim,
        r.nome AS reservatorio_nome,
        i.nome AS instituicao_nome
    FROM tbestacao e
    LEFT JOIN tbreservatorio r ON e.idreservatorio = r.idreservatorio
    LEFT JOIN tbinstituicao i ON r.idinstituicao = i.idinstituicao
    WHERE (p_instituicao_nome IS NULL OR i.nome = p_instituicao_nome)
      AND (p_reservatorio_nome IS NULL OR r.nome = p_reservatorio_nome)
    ORDER BY e.rotulo
    LIMIT p_limit_param
    OFFSET p_offset_param;
END;
$$;
